database:
    provider: mysql
    args: []
    kwargs:
        port: 3306
        host: localhost
        user: root
        passwd: digital
        db: synonymista
        # charset: utf8
run:
    host: 0.0.0.0
    port: 5050
